[[hints.enabled]]
action = "Copy"
post_processing = false
regex = '([0-9a-f]{12,128})|([[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3})'

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[[hints.enabled]]
command = "firefox"
post_processing = true
regex = "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "I"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true

[colors.hints.end]
background = "0xffffff"
foreground = "0x000000"

[colors.hints.start]
background = "0xffffff"
foreground = "0x000000"
