alias cp="cp -i"     # confirm before overwriting something
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB
alias np='nano -w PKGBUILD'
alias more=less
alias ls="lsd"
alias ll="ls -lahF"
alias lt='ls --tree'
alias x="cd ${GOPATH}/src/github.com/jbpratt78/x"
alias ~="cd ~"
alias ..="cd .."
alias ...="cd ../.."
alias grep='grep --color=auto'
alias weather="curl wttr.in/Birmingham,AL"
alias gc="git commit -vp"
alias ga="git add"
alias gd="git diff --cached"
alias gs="git status"
alias jq="gojq"
alias krepl="kotlinc-jvm"
alias gofmt="gofumpt"
alias goimports="gofumports"
alias gmodu="go list -u -m -json all | go-mod-outdated -direct -update"
alias cat="bat"
