format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmake\
$dotnet\
$golang\
$python\
$rust\
$aws\
$cmd_duration\
$line_break\
$status\
$character"""

[aws]
format = ' [$profile]($style) '
style = "bold blue"

[cmd_duration]
min_time = 500
format = "[$duration](bold yellow)"

[git_branch]
format = "[$symbol$branch]($style) "

[golang]
format = " [$version](bold cyan)"

[python]
format = ' [${version}(\($virtualenv\))]($style)'
